version: "3"

services:
  ssh_host1:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "5020:22"
      - "5030:27017"

  ssh_host2:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "5021:22"
      - "5031:27017"